name: Release

on:
  release:
    types: [ published ]

jobs:
  build:
    name: Build assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      - name: Build Linux AMD64
        run: |
          go build -o cmfive
          tar -czvf cmfive_${{ github.event.release.tag_name }}_linux_amd64.tar.gz cmfive LICENSE
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./cmfive_${{ github.event.release.tag_name }}_linux_amd64.tar.gz
          asset_name: cmfive_${{ github.event.release.tag_name }}_linux_amd64.tar.gz
          asset_content_type: application/zip
